version: "3"
services:

  db:
    restart: always
    image: mariadb:10.2
    environment:
      - "MYSQL_DATABASE=smigrator"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./mariadb:/var/lib/mysql

  web:
    build: .
    image: neetshin/smigrator
    restart: always
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/smigrator
