version: "3"
services:

  db:
    restart: always
    image: mariadb:10.2
    environment:
      - "MYSQL_DATABASE=smigrator"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./mariadb:/var/lib/mysql

  redis:
    restart: always
    image: redis:4.0-alpine
    ports:
      - "4000:4000"
    volumes:
      - ./redis:/data

  web:
    build: .
    image: neetshin/smigrator
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/smigrator
